"""empty message

Revision ID: 5b6e0c5e68ad
Revises: 59e4a7ec35b5
Create Date: 2018-07-07 18:34:19.416699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6e0c5e68ad'
down_revision = '59e4a7ec35b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('pic', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.String(length=64), nullable=False),
    sa.Column('area', sa.String(length=64), nullable=False),
    sa.Column('time', sa.String(length=64), nullable=False),
    sa.Column('intro', sa.String(length=64), nullable=False),
    sa.Column('show_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film')
    # ### end Alembic commands ###
